server:
  port: 0
bot:
  token: ${BOT_TOKEN:YOURTOKENHERE}
  embed:
    title: "TEST BOT"
    description: "TEST BOT"
    color: 2871056
    thumbnail:
      url: "https://cdn.discordapp.com/attachments/826929655851384922/852204578064564254/a_3596d9dbe4464e2d1cb9265d8ceb3ccf.png"
    footer:
      text: "TEST BOT"
logging:
  level:
    root: info